name: CI/CD pipeline

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configurar o JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Passo 3: Verificar a versão do Java
      - name: Verify Java Version
        run: java -version

      # Passo 4: Limpar e compilar o projeto
      - name: Clean and compile with Maven
        run: mvn -B package --file pom.xml

      # Passo 5: Executar os testes
      - name: Run tests
        run: mvn test


