name: CI/CD pipeline

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configurar o JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Passo 3: Verificar a versão do Java
      - name: Verify Java Version
        run: java -version

      # Passo 4: Limpar e compilar o projeto
      - name: Clean and compile with Maven
        run: mvn clean compile --file pom.xml

      # Passo 5: Executar os testes e capturar relatórios
      - name: Run tests
        run: mvn test --file pom.xml

      # Passo 6: Listar diretórios para depuração
      - name: List directories
        run: ls -R target || echo "Target directory not found"

      # Passo 7: Fazer upload dos relatórios Surefire (caso os testes falhem)
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
